apiVersion: v1
kind: Service
metadata:
  name: service-feedback
spec:
  selector:
    app: service-feedback
  type: NodePort
  ports:
    - name: http
      port: 8083
      nodePort: 31003

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-feedback
spec:
  selector:
    matchLabels:
      app: service-feedback
  replicas: 1
  template:
    metadata:
      labels:
        app: service-feedback
    spec:
      containers:
        - name: server
          image: vladstone13/service-feedback
          ports:
            - name: http
              containerPort: 8083

---